[evaluation_system]
admins=freva-admin
project_name=freva
project_website=https://freva.example.org
root_dir=/var/lib/freva/freva/core
directory_structure_type=central
base_dir_location=/var/lib/freva/freva/work
base_dir=freva
scheduler_system=local
scheduler_input_dir=/tmp/local_output
scheduler_output_dir=/var/lib/freva/freva/work/share/local
preview_path=/var/lib/freva/freva/work/share/preview
number_of_processes=6
project_data=/var/lib/freva/freva/work/data/crawl_my_data
db.host=freva.example.org
solr.host=freva.example.org
solr.port=8983
solr.core=files
