---
- name: Getting container engine
  include_tasks: "get_container_engine.yml"

- name: Set web container names
  set_fact:
    web_container_names: >-
      {{
        [web_name, web_cache_name]
        + ([web_proxy_name] if web_reverse_proxy | default(false) | bool else [])
      }}

- name: Clean up existing web containers and network
  command: "{{ docker_bin }} {{ item }}"
  loop:
    - "stop {{ web_container_names | join(' ') }}"
    - "rm -f {{ web_container_names | join(' ') }}"
    - "rmi -f ghcr.io/freva-org/freva-web:{{ web_version }}"
    - "network rm {{ web_name }}_{{ web_name }}"
  failed_when: false
  changed_when: true

- name: Clean up existing reverse proxy image
  ansible.builtin.command: "{{ docker_bin }} {{ item }}"
  loop:
    - "rmi -f ghcr.io/freva-org/freva-nginx:{{ proxy_version | default('latest') }}"
  when: web_reverse_proxy | default(false) | bool
  failed_when: false
  changed_when: true

- name: Pull required web containers
  ansible.builtin.command: "{{ docker_bin }} {{ item }}"
  loop:
    - "pull ghcr.io/freva-org/freva-web:{{ web_version }}"

- name: Pull reverse proxy container
  ansible.builtin.command: "{{ docker_bin }} {{ item }}"
  loop:
    - "pull ghcr.io/freva-org/freva-nginx:{{ proxy_version | default('latest') }}"
  when: web_reverse_proxy | default(false) | bool

- name: Create Docker network
  ansible.builtin.command: "{{ docker_bin }} network create {{ web_name }}_{{ web_name }} --ipv6"
  failed_when: false
  changed_when: true

- name: Cleaning volumes
  shell: >
    {{ docker_bin }} volume rm -f {{ item }}
  loop: "{{ volume_names  | default([]) }}"

- name: Creating directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ uid }}"
    group: "{{ gid }}"
  loop:
    - "{{ base_path }}/{{ project_name }}/compose_services"
    - "{{ web_device_path }}"


- name: Check whether SELinux is enabled
  ansible.builtin.command: getenforce
  register: selinux_status
  changed_when: false
  failed_when: false

- name: Set SELinux context rule for Django static volume
  ansible.builtin.shell: |
    semanage fcontext -a -t container_file_t '{{ web_device_path }}(/.*)?' \
    || semanage fcontext -m -t container_file_t '{{ web_device_path }}(/.*)?'
  register: static_selinux_context
  changed_when: static_selinux_context.rc == 0
  when: selinux_status.stdout in ["Enforcing", "Permissive"]

- name: Apply SELinux context to Django static volume
  ansible.builtin.command: restorecon -Rv {{ web_device_path }}
  changed_when: false
  when: selinux_status.stdout in ["Enforcing", "Permissive"]

- name: Removing old compose file
  file:
    path: "{{ compose_file }}.yml"
    state: absent

- name: Rendering templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - dest: "{{ compose_file }}-app.yml"
      src: web-compose-app.j2
    - dest: "{{ compose_file }}-maintenance.yml"
      src: web-compose-maintenance.j2
    - dest: "{{ systemd_unit_dir }}/{{ web_name }}.service"
      src: systemd-container.j2

- name: Create environment file
  copy:
    content: |
      # Controls which compose profile is active.
      # Set to FREVA_MAINTENANCE_MODE to "1" to start only nginx with
      # a maintenance page.
      # Set to "0" for normal operation (all services).
      FREVA_MAINTENANCE_MODE=0
    dest: "{{ env_path }}"
    mode: "0600"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    force: false

- name: Reload systemd
  systemd:
    daemon_reload: true
    scope: "{{ 'system' if ansible_become is true else 'user' }}"

- name: Enable and start web services
  systemd:
    name: "{{ web_name }}.service"
    enabled: true
    state: started
    scope: "{{ 'system' if ansible_become is true else 'user'}}"

- pause: seconds=30

- name: Check if service is running
  systemd:
    name: "{{ web_name }}"
    scope: "{{ 'system' if ansible_become is true else 'user'}}"
  register: service_status
  ignore_errors: true

- name: Fail if service is not running
  fail:
    msg: "{{ project_name }}-web service is not running"
  when: service_status.status.ActiveState != "active"
