---
- name: Running common tasks
  include_tasks: "common_tasks.yml"

- name: Stopping the services
  systemd:
    name: "{{ db_name }}"
    state: stopped
    enabled: false
    scope: "{{ 'system' if ansible_become is true else 'user'}}"
  ignore_errors: true
  failed_when: false

- name: Playing the {{ deployment_method }} tasks
  ansible.builtin.include_tasks:
    file: "{{ deployment_file | trim }}"
