{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freva.secretName" . }}
  labels:
    {{- include "freva.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_PASSWORD: {{ required "secrets.values.adminPassword is required when secrets.create=true" .Values.secrets.values.adminPassword | quote }}
  MYSQL_ROOT_PASSWORD: {{ required "secrets.values.adminPassword is required when secrets.create=true" .Values.secrets.values.adminPassword | quote }}
  MYSQL_PASSWORD: {{ required "secrets.values.databasePassword is required when secrets.create=true" .Values.secrets.values.databasePassword | quote }}
  REDIS_USERNAME: {{ .Values.secrets.values.redisUsername | quote }}
  REDIS_PASSWORD: {{ required "secrets.values.redisPassword is required when secrets.create=true" .Values.secrets.values.redisPassword | quote }}
  MONGO_APP_USER: {{ .Values.secrets.values.mongoUsername | quote }}
  MONGO_APP_PASSWORD: {{ required "secrets.values.mongoPassword is required when secrets.create=true" .Values.secrets.values.mongoPassword | quote }}
  OIDC_CLIENT_SECRET: {{ required "secrets.values.oidcClientSecret is required when secrets.create=true" .Values.secrets.values.oidcClientSecret | quote }}
{{- end }}
