[evaluation_system]
admins=freva
project_name=freva-dev
project_website=http://localhost:8080
root_dir=/data/config
directory_structure_type=local
base_dir=freva-dev
scheduler_system=local
scheduler_input_dir=/tmp/local_output
scheduler_output_dir=/tmp/local_output
preview_path=/opt/freva_web/static/preview
number_of_processes=2
project_data=/tmp/data
db.host=database-server
solr.host=search-server
solr.port=8983
solr.core=files
