---
- name: Include role variables
  ansible.builtin.include_vars: "{{ role_path }}/files/vars.yml"

- name: Run the Kubernetes deployment
  ansible.builtin.include_tasks: k8s-deployment.yml
  when: deployment_method == 'k8s'

- name: Run deployment with {{ deployment_method }}
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/systemd-based.yml"
  vars:
    deployment_file: >-
      {{ role_path }}/tasks/{{ deployment_method }}-deployment.yml
  when: deployment_method in ['quadlet', 'conda']
