---
- name: Include role variables
  ansible.builtin.include_vars: "{{ role_path }}/files/vars.yml"

- name: Run the Kubernetes deployment
  ansible.builtin.include_tasks: k8s-deployment.yml
  when: deployment_method == 'k8s'

- name: Run the systemd data-loader deployment
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/systemd-based.yml"
  when:
    - deployment_method in ['quadlet', 'conda']
    - not data_portal_scheduler_skip | default(false) | bool
