---
- name: Running common conda tasks
  ansible.builtin.include_tasks: >-
    {{ role_path }}/../../playbooks/tasks/conda.yml

- name: Get the web app
  ansible.builtin.unarchive:
    src: https://github.com/freva-org/freva-web/releases/download/{{ web_version }}/freva-web-bundle.tar.gz
    dest: "{{ data_dir }}/app"
    remote_src: true
    keep_newer: false

- name: Install pip dependencies
  ansible.builtin.shell:
    cmd: >
      {{ conda_path }}/bin/python -m pip install --no-input -U --progress-bar off --no-color --root-user-action ignore {{ pip_packages | join(' ') }}


- name: Adjusting web app ownership
  ansible.builtin.file:
    path: "{{ data_dir }}/app"
    state: directory
    recurse: true
    owner: "{{ uid }}"
    group: "{{ gid }}"

- name: Get free Redis port using Python
  ansible.builtin.shell: >
    {{ conda_path }}/bin/python3 -c
    "import socket; s=socket.socket(); s.bind(('', 0)); print(s.getsockname()[1]); s.close()"
  register: redis_port_result
  changed_when: false

- name: Creating environment file for redis
  ansible.builtin.template:
    src: "service.env.j2"
    dest: "{{ env_dir }}/redis.env"
    owner: "{{ uid }}"
    group: "{{ gid }}"
  vars:
    service_name: "{{ web_cache_name }}"
    _web_env_vars:
      API_LOG_DIR: "{{ data_dir }}/logs"
      API_CONFIG_DIR: "{{ data_dir }}/config"
      CONDA_PREFIX: "{{ conda_path }}"
      REDIS_PASSWORD: "{{ web_redis_password }}"
      REDIS_USERNAME: "{{ web_redis_username }}"
      REDIS_PORT: "{{ redis_port_result.stdout }}"

- name: Creating environment file for web app
  ansible.builtin.template:
    src: "service.env.j2"
    dest: "{{ env_path }}"
    owner: "{{ uid }}"
    group: "{{ gid }}"
  vars:
    service_name: "{{ web_name }}"
    _web_env_vars:
      ALLOWED_HOSTS: "{{ web_allowed_hosts | join(',') }}"
      API_LOG_DIR: "{{ data_dir }}/logs"
      CHATBOT_HOST: '{{ web_chatbot_host.replace("http://", "") }}'
      COLUMNS: "140"
      CONDA_PREFIX: "{{ conda_path }}"
      CSRF_TRUSTED_ORIGINS: "{{ web_csrf_trusted_origins | join(',') }}"
      DJANGO_SUPERUSER_EMAIL: "freva@dkrz.de"
      DJANGO_SUPERUSER_PASSWORD: "{{ root_passwd }}"
      EVALUATION_SYSTEM_CONFIG_FILE: "{{ core_root_dir | regex_replace('^~', ansible_facts.env.HOME) }}/freva/evaluation_system.conf"
      FREVA_REST_URL: 'http://{{ web_freva_rest_host.replace("http://", "") }}'
      FREVA_BIN: "{{ web_freva_bin }}"
      FREVA_WEB_CONFIG_FILE: "{{ web_config_file }}"
      REDIS_HOST: "localhost"
      REDIS_PASSWD: "{{ web_redis_password }}"
      REDIS_USER: "{{ web_redis_username }}"
      REDIS_PORT: "{{ redis_port_result.stdout }}"
      OIDC_DISCOVERY_URL: "{{ web_oidc_url }}"
      OIDC_CLIENT_SECRET: "{{ web_oidc_client_secret }}"
      OIDC_CLIENT_ID: "{{ web_oidc_client }}"
      SCHEDULER_HOST: "{{ web_scheduler_host | join(',') }}"
      STAC_BROWSER: "1"
      FREVA_MAINTENANCE_MODE: "0"

- name: Create systemd services
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ systemd_unit_dir }}/{{ item.dest }}.service"
  loop:
    - { src: systemd-conda-redis.j2, dest: "{{ web_cache_name }}" }
    - { src: systemd-conda-django.j2, dest: "{{ web_name }}" }

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    scope: "{{ 'system' if ansible_become is true else 'user' }}"

- name: Enable and start web services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    scope: "{{ 'system' if ansible_become is true else 'user' }}"
  loop:
    - "{{ web_cache_name }}.service"
    - "{{ web_name }}.service"

- name: Create Django user via manage.py shell
  when: debug | default(false)
  ansible.builtin.shell: >
    python manage.py shell -c
    "from django.contrib.auth import get_user_model;
    User = get_user_model();
    User.objects.filter(is_superuser=True).delete();
    u = User.objects.filter(username='{{ ansible_user }}').first() or
    User.objects.create_user(username='{{ ansible_user }}', password='{{ root_passwd }}');
    u.is_staff = True; u.is_superuser = True; u.save()"
  args:
    chdir: "{{ data_dir }}/app"
  environment:
    PATH: "{{ conda_path }}/bin:{{ ansible_facts.env.PATH }}"
    DJANGO_SUPERUSER_EMAIL: "freva@dkrz.de"
    DJANGO_SUPERUSER_PASSWORD: "{{ root_passwd }}"
    EVALUATION_SYSTEM_CONFIG_FILE: "{{ core_root_dir | regex_replace('^~', ansible_facts.env.HOME) }}/freva/evaluation_system.conf"
    FREVA_WEB_CONFIG_FILE: "{{ web_config_file }}"
