---
- name: Running common tasks
  ansible.builtin.include_tasks: >-
    {{ role_path }}/../../playbooks/tasks/common_tasks.yml

- name: Stop the web services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    scope: "{{ 'system' if ansible_become is true else 'user' }}"
  failed_when: false
  loop:
    - "{{ web_name }}"
    - "{{ web_cache_name }}"
    - "{{ web_obsolete_proxy_name }}"

- name: Removing old services files
  ansible.builtin.file:
    state: absent
    force: true
    path: "{{ systemd_unit_dir }}/{{ item }}.service"
  loop:
    - "{{ web_name }}"
    - "{{ web_cache_name }}"
    - "{{ web_obsolete_proxy_name }}"

- name: Run web deployment tasks
  ansible.builtin.include_tasks:
    file: "{{ deployment_file | trim }}"
