---
freva_deployment_root: "{{ role_path }}/../.."
service: web
ansible_become: "{{ web_ansible_become_user is defined and web_ansible_become_user != '' }}"
ansible_become_user: "{{ web_ansible_become_user | default('root') }}"
base_path: '{{ web_data_path | regex_replace("^~", ansible_facts.env.HOME) }}'
systemd_unit_dir: >-
  {{
    '/etc/systemd/system'
    if web_ansible_become_user is defined and web_ansible_become_user != ''
    else ansible_facts.env.HOME + '/.config/systemd/user'
  }}
web_device_path: >-
  {{
    (
      ['/srv/freva', project_name, 'static']
      if (web_ansible_become_user | default('')) != ''
      else [ansible_env.HOME, '.share', 'freva', project_name, 'static']
    ) | path_join
  }}
web_name: "{{ project_name }}-web"
web_cache_name: "{{ project_name }}-web-cache"
web_obsolete_proxy_name: "{{ project_name }}-web-proxy"
web_bind_address: "127.0.0.1"
web_port: 8000
web_config_file: "{{ core_root_dir | regex_replace('^~', ansible_facts.env.HOME) }}/freva/web/freva_web_conf.toml"
env_path: "{{ env_dir }}/{{ service }}.env"
old_compose_dir: '{{ web_data_path | regex_replace("^~", ansible_facts.env.HOME) }}/compose_services'
data_dir: "{{ base_path }}/{{ project_name }}/services/{{ service }}"
conda_path: "{{ data_dir }}/app/conda"
wipe: "{{ web_wipe }}"

conda_packages:
  - bleach
  - django-debug-toolbar
  - django-ipware
  - django-nose
  - django-webpack-loader
  - djangorestframework
  - fabric
  - freva
  - git
  - gunicorn
  - mysqlclient
  - paramiko
  - pip
  - pygtail
  - redis-py
  - toml
  - unidecode
  - redis-server
  - libxcrypt1
  - webpack-cli
  - nodejs

pip_packages:
  - django-datatable-view
  - django-templated-email
  - django-debug-toolbar-user-panel
  - django-compressor
  - django-bootstrap-v5
  - django-model-utils
  - djproxy
  - markdown

secret_keys:
  - OIDC_CLIENT_SECRET
  - OIDC_CLIENT_ID
  - REDIS_USER
  - REDIS_PASSWD
  - REDIS_PASSWORD
  - REDIS_USERNAME
